-- Salin dan jalankan skrip ini di SQL Editor pada Dashboard Supabase Anda

CREATE TABLE IF NOT EXISTS members (
  id BIGINT PRIMARY KEY,
  name TEXT NOT NULL,
  status TEXT NOT NULL,
  color TEXT NOT NULL,
  wa_number TEXT
);

CREATE TABLE IF NOT EXISTS winner_history (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  member_id BIGINT,
  name TEXT NOT NULL,
  win_date TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);
